name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HF}}
        run: git remote add space https://MohamedMoustafa:$HF_TOKEN@huggingface.co/spaces/MohamedMoustafa/Demo0
      
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF}}
        run: git push --force https://MohamedMoustafa:$HF_TOKEN@huggingface.co/spaces/MohamedMoustafa/Demo0 main
